[project]
name = "events-aggregator"
version = "0.1.0"
description = "Backend сервис-агрегатор для работы с системой управления событиями"
readme = "README.md"
authors = [
    { name = "Ilya Gorbachev", email = "ilya-gorbachev01@yandex.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "apscheduler>=3.11.3",
    "asyncpg>=0.31.0",
    "cachetools>=7.1.8",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sentry-sdk>=2.71.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "tenacity>=9.1.4",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.15.1",
    "respx>=0.23.1",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 88  # Значение по умолчанию для ruff, но отличается от PEP8
target-version = "py313"

extend-exclude = [
    "alembic/versions",  # Автогенерируемые миграции
]

[tool.ruff.lint]
select = [
    "ANN",      # flake8-annotations
    "ARG",      # flake8-unused-arguments
    "ASYNC",    # flake8-async
    "B",        # flake8-bugbear
    "C4",       # flake8-comprehensions
    "COM",      # flake8-commas
    "D",        # pydocstyle
    "E",        # pycodestyle
    "F",        # pyflakes
    "G",        # flake8-logging-format
    "I",        # isort
    "N",        # pep8-naming
    "PIE",      # flake8-pie
    "PLC0415",  # import-outside-top-level
    "PT",       # flake8-pytest-style
    "Q",        # flake8-quotes
    "RET",      # flake8-return
    "RUF",      # Ruff
    "SIM",      # flake8-simplify
    "TC",       # flake8-type-checking
    "UP",       # pyupgrade
    "W",        # pycodestyle (warnings)
]

ignore = [
    "ANN401",   # Dynamically typed expressions (typing.Any)
    "COM812",   # Checks for the absence of trailing commas
    "D100",     # Missing docstring in public module
    "D104",     # Missing docstring in public package
    "D107",     # Missing docstring in `__init__`
    "RUF001",   # Checks for ambiguous Unicode characters in strings
    "RUF002",   # Checks for ambiguous Unicode characters in docstrings
    "RUF003",   # Checks for ambiguous Unicode characters in comments
    "SIM108",   # Use ternary operator
]

unfixable = [
    "F841",   # Не удалять автоматически неиспользуемые переменные
    "ERA001", # Не удалять закомментированный код автоматически
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
