"""Add fields and modify the index for the OutboxMessage model.

Revision ID: 983ab9c808b7
Revises: 798fa4bcac1f
Create Date: 2026-09-30 14:28:55.903806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983ab9c808b7'
down_revision: Union[str, Sequence[str], None] = '798fa4bcac1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('outbox', sa.Column('last_error', sa.String(), nullable=True))
    op.drop_index(op.f('ix_outbox_pending'), table_name='outbox', postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('ix_outbox_pending', 'outbox', ['created_at', 'next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_pending', table_name='outbox', postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_outbox_pending'), 'outbox', ['created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_column('outbox', 'last_error')
    op.drop_column('outbox', 'next_attempt_at')
    # ### end Alembic commands ###
