"""add status and cancelled_at to tickets

Revision ID: adba57145cca
Revises: d0f7ab374737
Create Date: 2026-10-07 16:27:55.189834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adba57145cca'
down_revision: Union[str, Sequence[str], None] = 'd0f7ab374737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(), nullable=False, server_default="active"))
    op.add_column('tickets', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'cancelled_at')
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
