"""add status and cancelled_at in Ticket

Revision ID: f30355af2e16
Revises: d0f7ab374737
Create Date: 2026-10-06 16:57:03.813305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30355af2e16'
down_revision: Union[str, Sequence[str], None] = 'd0f7ab374737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(), nullable=False, server_default="active"))
    # ### end Alembic commands ###

    # server_default нужен только для backfill существующих строк на 'active';
    # дальше значение задаёт ORM (TicketStatus.ACTIVE по умолчанию).
    # Убираем DEFAULT только на PostgreSQL — SQLite не поддерживает ALTER COLUMN.

    if op.get_bind().dialect.name == "postgresql":
        op.alter_column("tickets", "status", server_default=None)

    op.add_column(
        "tickets",
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
    )
    
    op.add_column('tickets', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))

    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_column('tickets', 'cancelled_at')
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
